### ISSUE TITLE
Contributing instructions missing assembly_valheim_publicized.dll instructions

### ISSUE THREAD

**Issue by Alphy11** [mtnewton/valheim-gravekeeper#2]
Hi! I was trying to make a quick update to add the ability to only keep gear when you die, rather than keep everything.  I had it working before you made the upgrades to never even let the items move to the grave, but after the update, the project now depends on "assembly_valheim_publicized.dll" which I cannot find where that comes from.  Mind updating the contributing instructions?

**Comment by mtnewton** [comment]
Updated readme and references to publicized dlls, (https://github.com/mtnewton/valheim-mods/commit/9a5ed492c05cbbbaabba8e59ef7288b6d3c1b1a0)
let me know if there any any more problems 😃

**Comment by Alphy11** [comment]
@mtnewton thanks!
I was hoping you could help me out with one issue.  In the previous version you were able to access the original argument to `MoveInventoryToGrave` but now when I try to do so, it says it is inaccessible.  Any advice on how to grab the player inventory?

What I'm trying: ` static bool MoveInventoryToGrave_PrefixPatch(ref Inventory __instance, Inventory original)`

**Comment by mtnewton** [comment]
That looks correct. original should refer to the player inventory in this case.

There has been an update to Gravekeeper. Ability to keep all, or equipment, ammo, consumables, and hotbar. Each toggleable, take a look at the configs.
