### ISSUE TITLE
Gravekeeper: Delete specific items before grave creation, without keeping items in inventory

### ISSUE THREAD

**Issue by joecot** [mtnewton/valheim-gravekeeper#4]
There are currently 2 related config options:

- Options to keep specific items on your body when you die (as opposed to them going to your grave)
- Option to delete items from your grave (except the items kept on your body)

I really want a 3rd option:

- Option to keep specific items in your grave, and delete the rest.

For example, on death I want all my items to go to my grave, but I want to delete things like trophies. So that if possible, only 1 grave gets made instead of 2 if I have mods that increase inventory size. Currently, I can either keep items on my body, or leave all items in my grave. I can't say keep all but X items on my grave, and don't keep anything in my inventory. If I set KeepInventory.enabled=false, and DeleteItems=true, I keep no items on my body and my grave is empty.

Options I could see to add that would be:
- You could modify KeepInventory so that if Enabled=false but there are Keep options that are true, and DeleteItems=true, the grave is created without the items not marked to keep.
- You could add a KeepInventory.EnabledGrave or something to apply those options to the grave if KeepInventory.Enabled=false
- You could make a separate set of Grave configs to filter what gets kept in your grave.

**Comment by mtnewton** [comment]
Thank you for the suggestion.
A new version of Gravekeeper has been released and you can now be more specific in what you would like deleted from the grave.
