### ISSUE TITLE
ItemStacks does not work with other mods

### ISSUE THREAD

**Issue by JCimbal** [mtnewton/valheim-gravekeeper#5]
Hello,
I encountered the following issue when using the ItemStacks-Mod.
The stack sizes and weights are not applied when having another mod active.
This issue is only presented since the latest update two days ago.

Tested with the following mods:
BetterUI by Masa
EquipmentAndQuickSlots by RandyKnapp
ExploreTogether by Rolo
FloatingItems by castix

r2modman is used for installation.

Steps to reproduce:
1. Install r2modman
2. Install BepInExPack_Valheim Mod
3. Install ItemsStacks Mod
4. Start the game -> ItemStacks is working
5. Install any of the above-mentioned mods
6. Start the game -> ItemStacks is not working anymore

Expected behavior:
ItemStacks should work even though other mods are installed.

**Comment by mtnewton** [comment]
I was not able to reproduce.
Made a new profile in r2modman with only ItemStacks and see the increased stack size
added BetterUI, same
added the others mentioned, same
here is an image showing the mods loaded, and ingame increased item stacks next to better ui durability bars

![works for me](https://i.imgur.com/lXBjMzS.png)

A few questions:
1. did you click the 'Start Modded' button, i've accidentally clicked 'Start vanilla' a few times
2. is the config file present and contain item values you expect?
3. can you try from a fresh profile, do you get the same?

If none of those change anything, im not sure whats wrong, but we may be able to tell from the logs.
can you modify the BepInEx config to have in the `Logging.Disk` section : `WriteUnityLog=true` and `LogLevels=All`
start the game and enter a world with the mods stated above thats making ItemStacks not work.
In r2modman, go to `settings->browse profile folder`.
Inside the `BepInEx` folder can you upload the `LogOutput.log` file here.
If you want, you can also export and upload your profile as a file via `settings->export profile as file` to see if i can replicate that way

**Comment by JCimbal** [comment]
Hey,
Thank you for the fast reply.
I forgot to list one mod and this was actually the issue (haven't seen that it was still enabled)
Its the TripleBronze by KaceCottam.
It looks like there is a bug in that mod causing yours not to work.
When you enable the _bypass of the smelter by create_ function the mod throws an error into the log file and your mod is not working anymore. So I would assume this ticket can be closed.
